"""Backward-compatible shim — delegates to src.pipeline.chunker."""

from src.pipeline.chunker import (  # noqa: F401
    ATTACK_PHASE_MAP,
    CHAR_LIMIT,
    CHUNK_TOKEN_LIMIT,
    IGNORE_HEADINGS,
    KNOWN_TOOLS,
    MarkdownChunker,
    _attack_phase,
    _breadcrumb,
    _clean,
    _code_block_ranges,
    _detect_difficulty,
    _detect_os,
    _extract_cves,
    _find_tools,
    _has_code,
    _machine_name,
    _parse_box_info,
    _split_at_level,
    _split_into_paragraphs,
    chunk_file,
    chunk_text,
)

__all__ = [
    "ATTACK_PHASE_MAP",
    "CHAR_LIMIT",
    "CHUNK_TOKEN_LIMIT",
    "IGNORE_HEADINGS",
    "KNOWN_TOOLS",
    "MarkdownChunker",
    "_attack_phase",
    "_breadcrumb",
    "_clean",
    "_code_block_ranges",
    "_detect_difficulty",
    "_detect_os",
    "_extract_cves",
    "_find_tools",
    "_has_code",
    "_machine_name",
    "_parse_box_info",
    "_split_at_level",
    "_split_into_paragraphs",
    "chunk_file",
    "chunk_text",
]
